### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by AShedko** [JuliaImages/ImageSegmentation.jl#17]
I`m sure there are some.
For example:
```
WARNING: PriorityQueue{K, V}(::Type{K}, ::Type{V}) is deprecated, use PriorityQueue{K, V}() instead.
Stacktrace:
...
```
Maybe let the bot have his way with it?
https://github.com/apps/femtocleaner

**Comment by timholy** [comment]
It's already on, see e.g., https://github.com/JuliaImages/ImageSegmentation.jl/pull/12. I suspect it's an update to DataStructures that triggered this.

**Comment by AShedko** [comment]
Thanks

**Comment by timholy** [comment]
I'll reopen though, because it sounds like there's still a deprecation, just not one that femtocleaner can fix.

**Comment by kmsquire** [comment]
This is due to a recent change in DataFrames.jl  which brought the PriorityQueue interface up-to-date.
