### ISSUE TITLE
Watershed example not working

### ISSUE THREAD

**Issue by Red-Portal** [JuliaImages/ImageSegmentation.jl#22]
![image](https://user-images.githubusercontent.com/18320033/36075941-d574fa6a-0f98-11e8-8b1a-96037b77e598.png)
This is the suggested result,

running
```julia
using ImageView
imshow(labels_map(segments))
```

leads to 
![image](https://user-images.githubusercontent.com/18320033/36075954-f70c801c-0f98-11e8-98ce-946dbb5e8022.png)

Is this result correct?

**Comment by bioimage-analysis** [comment]
I'm just starting with Julia but I though I could help, although it's a pretty old post. The result is good, you are just missing a step. You need to mask the area that are not part of the beads as so:
```julia
imshow(labels_map(segments).* ~bw)
```

**Comment by Red-Portal** [comment]
Thanks for the answer. I think we'll have to update the example documentation sometime

**Comment by bioimage-analysis** [comment]
I guess it's a lot of work but I usually work with scikit-image and their [Gallery ](http://scikit-image.org/docs/stable/auto_examples/) is extremely useful. I'm actually in the process of trying several juliaimages function and compare them side by side with scikit-image just to be sure that I'm consistent when I work with Julia. Also to see if Julia function are any faster.

**Comment by Red-Portal** [comment]
That's really great. I think you could also compare with opencv-python and matlab. These are also really popular tools in the imaging community

**Comment by timholy** [comment]
Is this fixed or do the docs still need updating? (Note it's almost trivial to do this yourself, see https://help.github.com/articles/editing-files-in-another-user-s-repository/)

I just added a "landing page" for demos that's directly inspired by scikit-image's page (see #29), as well as instructions in the README about how to add more demos. I'd love to receive contributions.
