### ISSUE TITLE
Speed-up watershed segmentation using information from a binary image

### ISSUE THREAD

**Issue by VPetukhov** [JuliaImages/ImageSegmentation.jl#34]
Following the [example from the documentation](https://juliaimages.org/latest/imagesegmentation/#Watershed-1), currently segmentation is performed on the whole image, and later it's filtered with the binary mask. Though, using mask during the segmentation would allow to significantly reduce computation time, avoiding computation for background pixels.

How about adding new optional parameter `img_bin::Union{Array{Bool,2}, BitArray{2}, Nothing}=nothing` to the function? So the interface will be changed from

```julia
watershed(img::AbstractArray{T, N}, markers::AbstractArray{S,N})
```
to
```julia
watershed(img::AbstractArray{T, N}, markers::AbstractArray{S,N}, img_bin::Union{AbstractArray{Bool,2}, BitArray{2}, Nothing}=nothing)
```

On my example, new function works 3.5 times faster. If you think it's fine, I will create a pull request.

**Comment by timholy** [comment]
This sounds reasonable to me! But perhaps it would be better to make it a keyword argument? Perhaps called `mask` or something?

**Comment by VPetukhov** [comment]
> But perhaps it would be better to make it a keyword argument? Perhaps called mask or something?

Yep, perhaps it would be better. Thanks!
