### ISSUE TITLE
Make ImageSegmentation a subpackage of Images?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageSegmentation.jl#78]
Previously ImageSegmentation depends on `Images`, but now we're making it depending on `ImageCore` and `ImageFiltering`, so currently it's possible that we do `@reexport ImageSegmentation` in `Images`.

My vision on Images.jl is to move stable packages to Images.jl repo (https://github.com/JuliaImages/Images.jl/issues/898) and reexport them from Images.jl. And I would also like to make our centralized documentation juliaimages.org to Images-exclusive; this said, the current ImageFeatures should host its own documentation unless we make it depending on smaller dependencies and included by `Images` like `ImageSegmentation` (if we do this way).

**Comment by timholy** [comment]
> but now we're making it depending on ImageCore and ImageFiltering

~Indeed even the latter will be only a test dependency. But your core point stands, of course~ nvm, it's always been a dependency...
