### ISSUE TITLE
unseeded_region_growing returns MethodError

### ISSUE THREAD

**Issue by ghost** [JuliaImages/ImageSegmentation.jl#83]
I am unable to get any segmentation algorithm working, even using the example code found [here.](https://juliaimages.org/v0.21/imagesegmentation/#Algorithms-1) I believe the error is caused by the function `default_diff_fn`.

![Screen Shot 2021-09-11 at 3 29 12 PM](https://user-images.githubusercontent.com/39716203/132962072-93b119a0-a22e-4544-9da7-5b067ecb3ada.png)

![Screen Shot 2021-09-11 at 3 33 13 PM](https://user-images.githubusercontent.com/39716203/132962115-02c3d8c6-56bc-4da1-b805-b6533ba19232.png)

**Comment by timholy** [comment]
I think you must have some package incompatibility, perhaps because you switched environments. What version of ColorVectorSpace are you running? This shouldn't happen in a consistent environment. Can you post the results of `Pkg.status()`?

https://github.com/JuliaLang/julia/issues/35663

**Comment by ghost** [comment]
![Screen Shot 2021-09-12 at 9 24 31 AM](https://user-images.githubusercontent.com/39716203/132993391-03b9b7e4-ee4c-41ee-9b4a-4790245802c4.png)

**Comment by ghost** [comment]
It also fails (with the same error) in this environment:
![Screen Shot 2021-09-12 at 9 53 52 AM](https://user-images.githubusercontent.com/39716203/132994329-e4cad88e-3c3f-4177-beec-730824fd4dd3.png)

**Comment by originalsouth** [comment]
Can reproduce with ` [80713f31] ImageSegmentation v1.5.1` using `[c3611d14] ColorVectorSpace v0.9.7` on Julia v1.6.3.

**Comment by originalsouth** [comment]
@cheetahspots01 try working around the problem by doing `img = real.(img)` first.

**Comment by ahjulstad** [comment]
Something changed between v1.5.0 and v1.5.1.

This works (but changing to v1.5.1 does not):
```
begin
    import Pkg
    Pkg.activate(mktempdir())
    Pkg.add([
        Pkg.PackageSpec(name="Images"),
        Pkg.PackageSpec(name="ImageSegmentation", version="1.5.0"),
        Pkg.PackageSpec(name="TestImages"),
        Pkg.PackageSpec(name="ImageIO"),
        Pkg.PackageSpec(name="ImageMagick")
    ])
    Pkg.instantiate()
    using Images, ImageSegmentation, TestImages
end

##

begin
	img = testimage("coffee.png") # fullname
end;

# imshow(img)

##

begin
	seeds = [(CartesianIndex(200,200),1)]
	print(seeded_region_growing(img, seeds))
end
```

**Comment by ahjulstad** [comment]
but with the development version, it seems to work:
```
        Pkg.PackageSpec(name="Images", rev="master"),
        Pkg.PackageSpec(name="ImageSegmentation", rev="master"),
```

**Comment by johnnychen94** [comment]
With Images v0.25 and ImageSegmentation v1.7 released, it should work now.
