### ISSUE TITLE
output or convert a segmented image

### ISSUE THREAD

**Issue by Ken-B** [JuliaImages/ImageSegmentation.jl#9]
First of all, thank you both for all the good work you are doing! I'm no expert but I require some image segmentation for my work and I am very happy to see the progress. I'm especially looking forward to the mean shift algorithm.

For this issue, I wonder why the output type `SegmentedImage` does not contain an actual segmented image (unless I'm missing it)? Could you perhaps include a conversion function? At the moment I'm using the following:

```julia
valuetype{K,V}(d::Dict{K,V}) = V

function make_image(segm_im::ImageSegmentation.SegmentedImage)
    labels  = segm_im.image_indexmap
    means   = segm_im.segment_means
    imgsegm = zeros(valuetype(means), size(labels))
    for i in eachindex(imgsegm)
        imgsegm[i] = means[labels[i]]
    end
    imgsegm
end
```
Thank you. And let me know if and where I can assist.

**Comment by annimesh2809** [comment]
@Ken-B Thanks for praising our work! :smile: 

The term "actual segmented image" is a little unclear. Any segmentation algorithm partitions an image by assigning each pixel of the image to a specific label. Hence, the result of a segmentation can be conveyed through the Dict(Pixel => Label) (`image_indexmap`) alone.

If you are interested in the image generated by replacing each label in `image_indexmap` to its corresponding mean color, then you could try this:
```julia
julia> # seg is a `SegmentedImage`
         seg_means = map(i->seg.segment_means[i], seg.image_indexmap)
```

**Comment by Ken-B** [comment]
Thanks, that clarifies. The oneliner is more elegant than my function.
